{% set version = "2.0.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidybayes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidybayes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidybayes/tidybayes_{{ version }}.tar.gz
  sha256: 198a50042ae7257a997f6ddb0879e9fcdb88a166f8b0429bbad08205ea282f3f

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-hdinterval
    - r-arrayhelpers
    - r-coda
    - r-dplyr >=0.8.0
    - r-forcats
    - r-ggplot2 >=3.0.0
    - r-ggstance
    - r-magrittr
    - r-plyr
    - r-purrr >=0.2.3
    - r-rlang >=0.3.0
    - r-tibble
    - r-tidyr
    - r-tidyselect
  run:
    - r-base
    - r-hdinterval
    - r-arrayhelpers
    - r-coda
    - r-dplyr >=0.8.0
    - r-forcats
    - r-ggplot2 >=3.0.0
    - r-ggstance
    - r-magrittr
    - r-plyr
    - r-purrr >=0.2.3
    - r-rlang >=0.3.0
    - r-tibble
    - r-tidyr
    - r-tidyselect

test:
  commands:
    - $R -e "library('tidybayes')"           # [not win]
    - "\"%R%\" -e \"library('tidybayes')\""  # [win]

about:
  home: http://mjskay.github.io/tidybayes, https://github.com/mjskay/tidybayes
  license: GPL (>= 3)
  summary: Compose data for and extract, manipulate, and visualize posterior draws from Bayesian models ('JAGS', 'Stan', 'rstanarm', 'brms', 'MCMCglmm', 'coda', ...)
    in a tidy data format. Functions are provided to help extract tidy data frames of draws from Bayesian models and that generate point summaries and intervals in
    a tidy format. In addition, 'ggplot2' 'geoms' and 'stats' are provided for common visualization primitives like points with multiple uncertainty intervals, eye
    plots (intervals plus densities), and fit curves with multiple, arbitrary uncertainty bands.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: tidybayes
# Title: Tidy Data and 'Geoms' for Bayesian Models
# Version: 1.1.0
# Date: 2019-06-02
# Authors@R: c( person("Matthew", "Kay", role = c("aut", "cre"), email = "mjskay@umich.edu"), person("Timothy", "Mastny", role = "ctb", email = "tim.mastny@gmail.com") )
# Maintainer: Matthew Kay <mjskay@umich.edu>
# Description: Compose data for and extract, manipulate, and visualize posterior draws from Bayesian models ('JAGS', 'Stan', 'rstanarm', 'brms', 'MCMCglmm', 'coda', ...) in a tidy data format. Functions are provided to help extract tidy data frames of draws from Bayesian models and that generate point summaries and intervals in a tidy format. In addition, 'ggplot2' 'geoms' and 'stats' are provided for common visualization primitives like points with multiple uncertainty intervals, eye plots (intervals plus densities), and fit curves with multiple, arbitrary uncertainty bands.
# Depends: R (>= 3.5.0)
# Imports: plyr, dplyr (>= 0.8.0), tidyr, ggplot2 (>= 3.0.0), coda, purrr (>= 0.2.3), rlang (>= 0.3.0), ggstance, grid, forcats, HDInterval, arrayhelpers, tidyselect, tibble, magrittr
# Suggests: knitr, testthat, vdiffr (>= 0.3.0), svglite, rstan (>= 2.17.0), runjags, rjags, jagsUI, rstanarm (>= 2.18.2), emmeans, broom (>= 0.4.3), dotwhisker, MCMCglmm, bayesplot, modelr, brms (>= 2.9.0), cowplot, ggridges, covr, gdtools, rmarkdown, ggrepel, bindrcpp, RColorBrewer, gganimate, gifski, png, transformr
# License: GPL (>= 3)
# Language: en-US
# BugReports: https://github.com/mjskay/tidybayes/issues/new
# URL: http://mjskay.github.io/tidybayes, https://github.com/mjskay/tidybayes
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# LazyData: true
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2019-06-02 20:30:28 UTC; matth
# Author: Matthew Kay [aut, cre], Timothy Mastny [ctb]
# Repository: CRAN
# Date/Publication: 2019-06-02 21:10:03 UTC
