appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: UekxUjerik6bD9ILyQkeqEAlccvIHoDOnYT4FBg7D2Ot4beuPMkRLNmCbMIlrFmlNnVs08roNSPyiDBlFyZV91Dr86wvz1nbK5le+6CgiRHCu7e18rnaFDC+313Aoyw9cK2AbgnTLoAblcwoEG8utuXBG/emVC+voOTThno6BwB8vt28OVj/PuvuHUEvkHErAiFcQSzgk0a/zBDGiSj61aGTbipW072Kji2TGa5DPHWqA/o2I/YmWD/ArjEpan9WLeSWd+mIrRWwOZUOIFlAUBYOEE+xk2hP6yYrzyRoxOt65ZFufYOyrXtJAgBPsJA+2qgA4vNxVEzvMcEorvLxbbW7ve7bs+BmAB9Tz4yMNuh0tXJ2IO/QMkFFUB8YTnPkaerhUHW4HwMEQbMoSZoskdNn013RxEbMNSlDvQmyNIQjAf/Zg4YkoD6+jiSrUIjEY/jfshhcfA9tBPwLOycmeskBf1sqnDEGkDOsYtiFXPfsF5e6zVEDaLPr7ukRVpngOK63pfL2relUgezcxSztia9u7hrQMvdZRzElSf3fg2NtRhI/WUqFlUcqQi6rSc5AczDtdDxD0z/TMvCXIHwt1JdsON+NPJnsRMGOTBpoJGUlB8azlPXRmYUNm1bTM05525Zh4hiDgfRSmrQKPrevJ4O7f+q3OHRstyeh3cpldIg=
conda_forge_output_validation: true
